# Generated by Django 5.2.3 on 2025-06-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='intructor',
            new_name='instructor',
        ),
    ]
